### ISSUE TITLE
No module named kinet2pcb.__main__

### ISSUE THREAD

**Issue by ibkvictor** [devbisme/kinet2pcb#10]
* kinet2pcb version: 1.1.0
* Python version: python 3.8
* Operating System: mac os 11 Big sur

### Description

Generate pcb from netlist. I already generated the netlist using skidl, but the `generate_pcb()` function would not work because the footprints for my parts located in ${KICAD6_FOOTPRINT_DIR} were not found by skidl.

### What I Did
Next, I tried to use kinet2pcb as a standalone module to generate the pcb.
`python -m kinet2pcb -i kicad_netlist.net --libraries /Applications/KiCad/KiCad.app/Contents/SharedSupport/footprints/`

However, it returned with a module not found error. At other times, it returned with some specifics:
```
/Users/vagrant/kicad-mac-builder/build/kicad/src/kicad/pcbnew/action_plugin.cpp(163): assert "PgmOrNull()" failed in register_action().
/Applications/KiCad/KiCad.app/Contents/Frameworks/Python.framework/Versions/3.8/bin/python3.8: No module named kinet2pcb.__main__; 'kinet2pcb' is a package and cannot be directly executed
```

Thanks in advance for your assistance.

**Comment by devbisme** [comment]
It's always a good idea to include the SKiDL code that caused the problem so others can try it themselves.

Also, `kinet2pcb` should be executable as a script. There is no reason to run it as a module. Try `kinet2pcb -h` to see if you have it installed on your system.
