### ISSUE TITLE
Use `net.get_pins()` instead of `net.pins`

### ISSUE THREAD

**Issue by programmer4567** [devbisme/kinet2pcb#12]
* kinet2pcb version: 1.1.0
* Python version: 3.11.3
* Operating System: Linux

### Description

If a pin does not have a `.ref`, an attribute error is raised and caught (for the incorrect reason - see code block below) and the old PCBNEW api is attempted, which in turn causes another attribute error because the new PCBNEW api should have been used (in my case). In the example below, pin 0 in net 2 (`netlist.nets[2].pins[0]`) does not have `.ref` causing the problem.
```python
>>> netlist.nets[2].pins
[Pin ???///UNSPECIFIED, Pin Q1/2/S/UNSPECIFIED, Pin R2/1/1/INPUT]
```

### What I Did

Solution: `net.get_pins()` should be used instead of `net.pins` in [the for loop in line 259](https://github.com/devbisme/kinet2pcb/blob/1547858f39fc8610c28379c3cb0cfeb403a5dfb4/kinet2pcb/kinet2pcb.py#L259)

Relevant block of code in [the source](https://github.com/devbisme/kinet2pcb/blob/1547858f39fc8610c28379c3cb0cfeb403a5dfb4/kinet2pcb/kinet2pcb.py#L259)
```python
for pin in net.pins:
  
  # Find the PCB module pad for the current part pin.
  pad = None
  try:
      # Newer PCBNEW API.
      module = brd.FindFootprintByReference(pin.ref)
      if module:
          pad = module.FindPadByNumber(pin.num)
  except AttributeError:
      # Older PCBNEW API.
      module = brd.FindModuleByReference(pin.ref)
      if module:
          pad = module.FindPadByName(pin.num)
```

**Comment by devbisme** [comment]
Thanks for the error report and the fix. I've released a new 1.1.1 version.
