### ISSUE TITLE
Lib URI expand invalid assumption

### ISSUE THREAD

**Issue by adamws** [devbisme/kinet2pcb#4]
* kinet2pcb version: 0.1.0
* Python version: 3.6.9
* KiCad version 5.1.5
* Operating System: Ubuntu 18.04.1 LTS

### Description
Following code has no effect:
```
# Expand variables and ~ in the URI.
uri = os.path.expandvars(os.path.expanduser(uri))
```
because variables like `KISYSMOD` (used in `fp_lib_table`) are not system environment variables (at least by default)

### What I Did
workaround (could be mentioned in docs)
`KISYSMOD=/usr/share/kicad/modules kinet2pcb -i mynetlist.net` 
not sure if it is possible to obtain `KISYSMOD` value via KiCad python API.

**Comment by xesscorp** [comment]
The latest release on Pypi (0.1.1) should fix this problem. Let me know if you try it. Thanks!
